### ISSUE TITLE
Мелкие текстовые правки Android

### ISSUE THREAD

**Issue by helpmebro** [helpmebro/fixing#6]
Save Changes = Speichern
Add picture = Profilfoto hinzufügen
Change Picture = Profilfoto ändern

Keine freien Helfer um НЕ ВЕРНЫЙ ПЕРЕВОД!
Верно: Bros in der Nähe wurden benachrichtigt. Keine Sorge, es wird Ihnen schon jemand helfen!

**Comment by HaGrIL** [comment]
исправлено
